### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by pwang7**

### CODE REVIEW

**Comment by laforest** [comment]
Thank you for spotting the documentation typo.

However, I don't agree with renaming the Register inside the Register_Toggle module.
Sometimes there is no further information to carry with a module instance name, and here the Register_Toggle module itself denotes what the Register is for. 

Could you please undo that last change, and I can accept the pull request.

**Comment by pwang7** [comment]
> Thank you for spotting the documentation typo.
> 
> However, I don't agree with renaming the Register inside the Register_Toggle module.
> Sometimes there is no further information to carry with a module instance name, and here the Register_Toggle module itself denotes what the Register is for.
> 
> Could you please undo that last change, and I can accept the pull request.

Done.

Just spot more typo, `ADDR_WIDTH**2` -> `2**ADDR_WIDTH`.

**Comment by laforest** [comment]
Thank you!

**Comment by pwang7** [comment]
BTW, will you continue writing this book?
Your book is very helpful~

**Comment by laforest** [comment]
Oh yes. I've been busy with other parts of the book for a while. I have an update going out soon.
I'm glad you are finding it helpful. Thank you!

**Pull request merged**
